### ISSUE TITLE
Questions regarding generalization

### ISSUE THREAD

**Issue by netconstructor** [cutting-room-floor/glower#1]
First of all... Great idea - interactivity of polygons is something I have been trying to achieve for months now using different methods. The BEST and quickest approach I have seen to date while maintaining data accuracy remains that of the recently released giscloud.com guys.

Now, in terms of this project, I would be interest to know how yours compares in terms of speed and accuracy and generalization (especially when dealing with thousands or even a million feature polygons)?

One thing which struck me right away is that there seems to be a real issue in terms of accuracy using your approach. Could it be that this is just due to me using an iPad or is this a known problem using a UTF-grid as the means of pushing the data to the canvas? Also, in terms of performance/accuracy is this approach better than pushing vector data through clipped/simplified JSON tiles using x/y/z coordinates?

Chris

**Comment by tmcw** [comment]
Hi Chris,

> Now, in terms of this project, I would be interest to know how yours compares in terms of speed and accuracy and generalization (especially when dealing with thousands or even a million feature polygons)?

Since they're entirely different approaches, I haven't really done a 'head to head competition', and I think that one's a bit dishonest, much like the giscloud blog post. This lets you have accurate, detailed base maps, and interaction thereof. Pure vector rendering generally allows you to have rather ugly basemaps and interaction thereof. 'Running numbers' is silly, because the product and the production is wildly different, and I wouldn't want to do something so misleading.

> One thing which struck me right away is that there seems to be a real issue in terms of accuracy using your approach. 

Can you be more specific? What problem of accuracy? Provide a screenshot, maybe?

> Also, in terms of performance/accuracy is this approach better than pushing vector data through clipped/simplified JSON tiles using x/y/z coordinates?

Better is a relative term. This approach is better because it degrades to normal interactivity in older browsers, rather than completely failing like a complete-vector approach. And, with a more precise grid, it'll end up being very similar in accuracy/resolution to what-have-you simplified polygons.

**Comment by netconstructor** [comment]
would it make any sense to utilize http://mbostock.github.com/d3/ to render vectors in your opinion?

**Comment by tmcw** [comment]
No: as noted before - this isn't rendering vectors, it's rendering rasters. And d3 doesn't really provide any assistance in rendering vectors - it's a great visualization library, and focuses on other problems.
